version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test-build-and-publish:
    docker:
      # specify the version you desire here
      - image: circleci/node:16.20.0-browsers

    working_directory: ~/CustomAuth

    steps:
      - checkout
      - run: npm install
      - run: npm run semantic-release #Release to npm

workflows:
  test-build-and-publish:
    jobs:
      - test-build-and-publish