version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-build-and-publish:
    docker:
      # specify the version you desire here
      - image: cimg/node:21.4.0

    working_directory: ~/CustomAuth

    steps:
      - checkout
      - run: npm install
      - run: npm run semantic-release #Release to npm

workflows:
  test-build-and-publish:
    jobs:
      - test-build-and-publish